"""Document analysis module using Ollama LLM.

This module handles communication with the local Ollama API to analyze
document content and generate metadata (filename and category suggestions).
"""

import json
import logging
import time
from typing import Dict, Optional

import requests

from .config import Config

logger = logging.getLogger(__name__)


class DocumentMetadata:
    """Data class for document metadata generated by LLM.

    Attributes:
        filename: Suggested filename in format 'YYYY-MM-DD_Topic_Keywords'.
        category: Suggested category for folder organization.
    """

    def __init__(self, filename: str, category: str):
        """Initialize DocumentMetadata.

        Args:
            filename: The suggested filename (without extension).
            category: The suggested category/folder name.
        """
        self.filename = filename
        self.category = category

    def to_dict(self) -> Dict[str, str]:
        """Convert metadata to dictionary format.

        Returns:
            Dictionary with 'filename' and 'category' keys.
        """
        return {
            "filename": self.filename,
            "category": self.category
        }

    @classmethod
    def from_dict(cls, data: Dict[str, str]) -> "DocumentMetadata":
        """Create DocumentMetadata from dictionary.

        Args:
            data: Dictionary containing 'filename' and 'category'.

        Returns:
            DocumentMetadata instance.
        """
        return cls(
            filename=data.get("filename", f"Scan_{int(time.time())}"),
            category=data.get("category", "Unsorted")
        )


class OllamaAnalyzer:
    """Analyzes document content using local Ollama LLM.

    This class communicates with a locally running Ollama instance to
    analyze document content and generate structured metadata for filing.

    Attributes:
        model_name (str): Name of the Ollama model to use.
        api_url (str): URL of the Ollama API endpoint.
        content_preview_length (int): Maximum content length to send to LLM.
    """

    def __init__(
        self,
        model_name: str = Config.MODEL_NAME,
        api_url: str = Config.OLLAMA_URL,
        content_preview_length: int = Config.CONTENT_PREVIEW_LENGTH
    ):
        """Initialize the OllamaAnalyzer.

        Args:
            model_name: Name of the Ollama model (e.g., 'llama3.2').
            api_url: Full URL to the Ollama API generate endpoint.
            content_preview_length: Max characters to include in analysis.
        """
        self.model_name = model_name
        self.api_url = api_url
        self.content_preview_length = content_preview_length
        logger.info(f"OllamaAnalyzer initialized with model: {model_name}")

    def analyze_document(self, content: str) -> DocumentMetadata:
        """Analyze document content and generate metadata.

        Sends document content to Ollama LLM for analysis and extracts
        structured metadata (filename and category suggestions).

        Args:
            content: The extracted text content of the document.

        Returns:
            DocumentMetadata object with filename and category suggestions.
        """
        # Handle empty or very short content
        if len(content.strip()) < 10:
            logger.warning("Content too short for meaningful analysis")
            return self._create_fallback_metadata("Review")

        logger.debug(f"Analyzing content ({len(content)} characters)")

        try:
            metadata_dict = self._call_ollama_api(content)
            metadata = DocumentMetadata.from_dict(metadata_dict)
            logger.info(
                f"Analysis successful: {metadata.filename} → {metadata.category}"
            )
            return metadata

        except Exception as e:
            logger.error(f"Document analysis failed: {e}", exc_info=True)
            return self._create_fallback_metadata("AI_Error")

    def _call_ollama_api(self, content: str) -> Dict[str, str]:
        """Make API call to Ollama and parse response.

        Args:
            content: Document content to analyze.

        Returns:
            Dictionary with 'filename' and 'category' keys.

        Raises:
            requests.RequestException: If API call fails.
            json.JSONDecodeError: If response is not valid JSON.
        """
        # Prepare the prompt
        prompt = self._build_prompt(content)

        # Build the API payload
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "format": "json"
        }

        logger.debug(f"Sending request to Ollama API: {self.api_url}")

        # Make the API request
        response = requests.post(
            self.api_url,
            json=payload,
            timeout=60  # 60 second timeout
        )
        response.raise_for_status()

        # Parse the response
        response_data = response.json()
        llm_response = response_data.get("response", "")

        if not llm_response:
            raise ValueError("Empty response from Ollama API")

        # Parse the JSON response from LLM
        metadata = json.loads(llm_response)

        # Validate required fields
        if "filename" not in metadata or "category" not in metadata:
            raise ValueError("Response missing required fields")

        logger.debug(f"Parsed metadata: {metadata}")
        return metadata

    def _build_prompt(self, content: str) -> str:
        """Build the analysis prompt for the LLM.

        Args:
            content: Document content to include in prompt.

        Returns:
            Formatted prompt string.
        """
        # Truncate content to configured length
        content_preview = content[:self.content_preview_length]

        prompt = (
            f"Analysiere diesen Dokumententext. "
            f"Antworte strikt im JSON-Format mit zwei Feldern: 'filename' und 'category'. "
            f"1. filename: Format 'YYYY-MM-DD_Thema_Schlagwort' (ohne Dateiendung). "
            f"2. category: Eine Kategorie für die Ordnerstruktur "
            f"(z.B. 'Rechnungen', 'Verträge', 'Steuer', 'Privat', 'Gesundheit', 'Versicherung'). "
            f"Antworte NUR mit JSON, keine zusätzlichen Erklärungen. "
            f"\n\nInhalt:\n{content_preview}"
        )

        return prompt

    def _create_fallback_metadata(self, reason: str) -> DocumentMetadata:
        """Create fallback metadata when analysis fails.

        Args:
            reason: Reason for fallback (e.g., 'Review', 'AI_Error').

        Returns:
            DocumentMetadata with timestamped filename and review category.
        """
        timestamp = int(time.time())
        return DocumentMetadata(
            filename=f"Scan_{reason}_{timestamp}",
            category="Inbox_Review"
        )

    def check_connection(self) -> bool:
        """Check if Ollama API is accessible.

        Returns:
            True if API is accessible, False otherwise.
        """
        try:
            # Try to reach the API (use a simpler endpoint if available)
            response = requests.get(
                self.api_url.replace("/api/generate", "/"),
                timeout=5
            )
            logger.info("Ollama API connection successful")
            return True
        except Exception as e:
            logger.error(f"Cannot connect to Ollama API: {e}")
            return False
